spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: xyz
            client-secret: zyx
          github:
            client-id: zxcz
            client-secret: sfa
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  batch:
    jdbc:
      initialize-schema: always
